### ISSUE TITLE
frontend/qml: Figure out a way to test it

### ISSUE THREAD

**Issue by quarnster** [limetext/lime#373] opened 2014-09-14 14:15 UTC
To prevent regressions...

**Comment by pjoe** [comment] 2015-01-24 17:06
QML has a testing framework that might be suited for this: http://doc.qt.io/qt-5/qtquick-qtquicktest.html

I have experience using this in my day job, feel free to contact me on IRC

**Comment by erbridge** [comment] 2015-04-17 12:49
Duplicate of #380.

**Closed by erbridge** 2015-04-17 12:49 UTC
Labels: frontend, qml, test
